# Generated by Django 2.1.3 on 2019-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('size', models.IntegerField(max_length=50000)),
                ('status', models.CharField(max_length=100)),
                ('datetime_file', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
    ]
