# Generated by Django 2.1.3 on 2019-12-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileObj',
            new_name='File',
        ),
    ]
